// Async actions
// export const FETCH_FCM_TOKEN_REQUEST = "FETCH_FCM_TOKEN_REQUEST";
// export const FETCH_FCM_TOKEN_FAILURE = "FETCH_FCM_TOKEN_FAILURE";
// export const FETCH_FCM_TOKEN_SUCCESS = "FETCH_FCM_TOKEN_SUCCESS";
//
// export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
// export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
// export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
//
// export const FETCH_PLANNING_APPS_REQUEST = "FETCH_PLANNING_APPS_REQUEST";
// export const FETCH_PLANNING_APPS_FAILURE = "FETCH_PLANNING_APPS_FAILURE";
// export const FETCH_PLANNING_APPS_SUCCESS = "FETCH_PLANNING_APPS_SUCCESS";

export const FETCH_FCM_TOKEN = "FETCH_FCM_TOKEN";
export const FETCH_USER = "FETCH_USER";
export const FETCH_PLANNING_APPS = "FETCH_PLANNING_APPS";

// Synchronous actions
export const FOCUS_LOCATION = "FOCUS_LOCATION";
